[package]
name = "call_list"
version = "0.1.0"
edition = "2021"

[dependencies]
# raalog.workspace = true
# toml.workspace = true
toml = "0.8.8"
raalog = { git = "https://github.com/AlexanderARodin/raalog.git", tag="v0.2.0" }

